/* eslint-disable */

module.exports = {
	"fenToyuan": "change",
	"inValidToText": "change",
	"removeLastetZero": "change",
	"spliceLineBreak": "change",
	"strToDateFomat": "change",
	"strToNumber": "change",
	"toDecimal": "change",
	"toLowerCase": "change",
	"toUpperCase": "change",
	"trimLR": "change",
	"delInvalidProperty": "common",
	"delInvisibleStr": "common",
	"delLineBreak": "common",
	"hasOwn": "common",
	"is": "common",
	"getBase64": "file",
	"getExt": "file",
	"getDisplayName": "get",
	"isArray": "is/isArray",
	"isBoolean": "is/isBoolean",
	"isClassComponent": "is/isClassComponent",
	"isEmpty": "is/isEmpty",
	"isEmptyObj": "is/isEmpty",
	"isNoValue": "is/isEmpty",
	"isFunction": "is/isFunction",
	"isInValid": "is/isInValid",
	"isNull": "is/isNull",
	"isNumber": "is/isNumber",
	"isObject": "is/isObject",
	"isPromise": "is/isPromise",
	"isString": "is/isString",
	"hasSymbol": "is/isSymbol",
	"isSymbol": "is/isSymbol",
	"shams": "is/isSymbol",
	"isUndefined": "is/isUndefined",
	"sortTime": "sort",
	"timeInterval": "time",
	"getParam": "url",
	"getParams": "url",
	"paramParse": "url",
	"idCardValidate": "validate",
	"regExp": "validate"
};